### ISSUE TITLE
Enhanced autostart 

### ISSUE THREAD

**Issue by AndyDroid10X** [Vanilla-OS/vanilla-control-center#141]
Now it's too hard in GNOME to add a script to autostart, as Gnome Tweaks tool offers autostart only for installed apps with entry in menu. Would be great if one could add any script to the autostart using GUI.

**Comment by kbdharun** [comment]
> Now it's too hard in GNOME to add a script to autostart, as Gnome Tweaks tool offers autostart only for installed apps with entry in menu. Would be great if one could add any script to the autostart using GUI.

Have you tried this with VSO tasks (https://github.com/Vanilla-OS/vanilla-system-operator)?

**Comment by AndyDroid10X** [comment]
Yeah it's very powerful, but I need user-specific autostart.

**Comment by mirkobrombin** [comment]
You can use vso tasks for user tasks, they are stored per user. The vanilla control center is going to be deprecated since we are moving everything inside GNOME Settings itself https://github.com/Vanilla-OS/vanilla-control-center/issues/92 so this issue should probably be started in the os repository instead.
